export type ColumnDef = {
  key: string;
  label: string;
  shortLabel?: string;
  importance: 'important' | 'all';
  kind: 'text' | 'int' | 'pct' | 'money';
  tooltip?: string;
};

const BASE_COLUMNS: ColumnDef[] = [
  {
    key: 'search_query_raw',
    label: 'Search Query',
    shortLabel: 'Query',
    importance: 'important',
    kind: 'text',
  },
  {
    key: 'search_query_volume',
    label: 'Search Query Volume',
    shortLabel: 'Volume',
    importance: 'important',
    kind: 'int',
  },
  {
    key: 'search_query_score',
    label: 'Search Query Score',
    shortLabel: 'Score',
    importance: 'all',
    kind: 'int',
  },
  {
    key: 'impressions_total',
    label: 'Impressions (Market)',
    shortLabel: 'Impr (Mkt)',
    importance: 'important',
    kind: 'int',
  },
  {
    key: 'impressions_self',
    label: 'Impressions (Self)',
    shortLabel: 'Impr (Self)',
    importance: 'important',
    kind: 'int',
  },
  {
    key: 'impressions_self_share',
    label: 'Impression Share (Self)',
    shortLabel: 'Impr Share',
    importance: 'important',
    kind: 'pct',
  },
  {
    key: 'clicks_total',
    label: 'Clicks (Market)',
    shortLabel: 'Clicks (Mkt)',
    importance: 'important',
    kind: 'int',
  },
  {
    key: 'clicks_self',
    label: 'Clicks (Self)',
    shortLabel: 'Clicks (Self)',
    importance: 'important',
    kind: 'int',
  },
  {
    key: 'clicks_self_share',
    label: 'Click Share (Self)',
    shortLabel: 'Click Share',
    importance: 'important',
    kind: 'pct',
  },
  {
    key: 'clicks_rate_per_query',
    label: 'Click Rate / Query',
    shortLabel: 'Click Rate',
    importance: 'all',
    kind: 'pct',
  },
  {
    key: 'clicks_price_median_total',
    label: 'Median Click Price (Market)',
    shortLabel: 'Click $ (Mkt)',
    importance: 'all',
    kind: 'money',
  },
  {
    key: 'clicks_price_median_self',
    label: 'Median Click Price (Self)',
    shortLabel: 'Click $ (Self)',
    importance: 'all',
    kind: 'money',
  },
  {
    key: 'clicks_same_day_ship',
    label: 'Clicks Same-Day Ship',
    shortLabel: 'Clicks SD',
    importance: 'all',
    kind: 'int',
  },
  {
    key: 'clicks_1d_ship',
    label: 'Clicks 1-Day Ship',
    shortLabel: 'Clicks 1D',
    importance: 'all',
    kind: 'int',
  },
  {
    key: 'clicks_2d_ship',
    label: 'Clicks 2-Day Ship',
    shortLabel: 'Clicks 2D',
    importance: 'all',
    kind: 'int',
  },
  {
    key: 'cart_adds_total',
    label: 'Cart Adds (Market)',
    shortLabel: 'Cart Adds (Mkt)',
    importance: 'important',
    kind: 'int',
  },
  {
    key: 'cart_adds_self',
    label: 'Cart Adds (Self)',
    shortLabel: 'Cart Adds (Self)',
    importance: 'important',
    kind: 'int',
  },
  {
    key: 'cart_adds_self_share',
    label: 'Cart Add Share (Self)',
    shortLabel: 'Cart Share',
    importance: 'important',
    kind: 'pct',
  },
  {
    key: 'cart_add_rate_per_query',
    label: 'Cart Add Rate / Query',
    shortLabel: 'Cart Rate',
    importance: 'all',
    kind: 'pct',
  },
  {
    key: 'cart_adds_price_median_total',
    label: 'Median Cart Price (Market)',
    shortLabel: 'Cart $ (Mkt)',
    importance: 'all',
    kind: 'money',
  },
  {
    key: 'cart_adds_price_median_self',
    label: 'Median Cart Price (Self)',
    shortLabel: 'Cart $ (Self)',
    importance: 'all',
    kind: 'money',
  },
  {
    key: 'cart_adds_same_day_ship',
    label: 'Cart Adds Same-Day Ship',
    shortLabel: 'Cart SD',
    importance: 'all',
    kind: 'int',
  },
  {
    key: 'cart_adds_1d_ship',
    label: 'Cart Adds 1-Day Ship',
    shortLabel: 'Cart 1D',
    importance: 'all',
    kind: 'int',
  },
  {
    key: 'cart_adds_2d_ship',
    label: 'Cart Adds 2-Day Ship',
    shortLabel: 'Cart 2D',
    importance: 'all',
    kind: 'int',
  },
  {
    key: 'purchases_total',
    label: 'Purchases (Market)',
    shortLabel: 'Purch (Mkt)',
    importance: 'important',
    kind: 'int',
  },
  {
    key: 'purchases_self',
    label: 'Purchases (Self)',
    shortLabel: 'Purch (Self)',
    importance: 'important',
    kind: 'int',
  },
  {
    key: 'purchases_self_share',
    label: 'Purchase Share (Self)',
    shortLabel: 'Purch Share',
    importance: 'important',
    kind: 'pct',
  },
  {
    key: 'purchases_rate_per_query',
    label: 'Purchase Rate / Query',
    shortLabel: 'Purch Rate',
    importance: 'all',
    kind: 'pct',
  },
  {
    key: 'purchases_price_median_total',
    label: 'Median Purchase Price (Market)',
    shortLabel: 'Purch $ (Mkt)',
    importance: 'all',
    kind: 'money',
  },
  {
    key: 'purchases_price_median_self',
    label: 'Median Purchase Price (Self)',
    shortLabel: 'Purch $ (Self)',
    importance: 'all',
    kind: 'money',
  },
  {
    key: 'purchases_same_day_ship',
    label: 'Purchases Same-Day Ship',
    shortLabel: 'Purch SD',
    importance: 'all',
    kind: 'int',
  },
  {
    key: 'purchases_1d_ship',
    label: 'Purchases 1-Day Ship',
    shortLabel: 'Purch 1D',
    importance: 'all',
    kind: 'int',
  },
  {
    key: 'purchases_2d_ship',
    label: 'Purchases 2-Day Ship',
    shortLabel: 'Purch 2D',
    importance: 'all',
    kind: 'int',
  },
  {
    key: 'search_query_norm',
    label: 'Search Query Norm',
    shortLabel: 'Query Norm',
    importance: 'all',
    kind: 'text',
  },
  {
    key: 'week_start',
    label: 'Week Start',
    importance: 'all',
    kind: 'text',
  },
  {
    key: 'week_end',
    label: 'Week End',
    importance: 'all',
    kind: 'text',
  },
  {
    key: 'reporting_date',
    label: 'Reporting Date',
    importance: 'all',
    kind: 'text',
  },
  {
    key: 'exported_at',
    label: 'Exported At',
    importance: 'all',
    kind: 'text',
  },
  {
    key: 'scope_type',
    label: 'Scope Type',
    importance: 'all',
    kind: 'text',
  },
  {
    key: 'scope_value',
    label: 'Scope Value',
    importance: 'all',
    kind: 'text',
  },
  {
    key: 'keyword_id',
    label: 'Keyword ID',
    importance: 'all',
    kind: 'text',
  },
];

const DERIVED_COLUMNS: ColumnDef[] = [
  {
    key: 'market_ctr',
    label: 'Market CTR',
    shortLabel: 'CTR (Mkt)',
    importance: 'important',
    kind: 'pct',
  },
  {
    key: 'self_ctr',
    label: 'Self CTR',
    shortLabel: 'CTR (Self)',
    importance: 'important',
    kind: 'pct',
  },
  {
    key: 'market_cvr',
    label: 'Market CVR',
    shortLabel: 'CVR (Mkt)',
    importance: 'important',
    kind: 'pct',
  },
  {
    key: 'self_cvr',
    label: 'Self CVR',
    shortLabel: 'CVR (Self)',
    importance: 'important',
    kind: 'pct',
  },
  {
    key: 'self_ctr_index',
    label: 'Self CTR Index',
    shortLabel: 'CTR Index',
    importance: 'important',
    kind: 'pct',
  },
  {
    key: 'self_cvr_index',
    label: 'Self CVR Index',
    shortLabel: 'CVR Index',
    importance: 'important',
    kind: 'pct',
  },
  {
    key: 'cart_add_rate_from_clicks_market',
    label: 'Cart Add / Clicks (Market)',
    shortLabel: 'Cart/Click M',
    importance: 'important',
    kind: 'pct',
  },
  {
    key: 'cart_add_rate_from_clicks_self',
    label: 'Cart Add / Clicks (Self)',
    shortLabel: 'Cart/Click S',
    importance: 'important',
    kind: 'pct',
  },
];

const ALL_COLUMNS: ColumnDef[] = [...BASE_COLUMNS, ...DERIVED_COLUMNS];

const IMPORTANT_KEYS: string[] = [
  'search_query_raw',
  'search_query_volume',
  'impressions_total',
  'impressions_self',
  'impressions_self_share',
  'clicks_total',
  'clicks_self',
  'clicks_self_share',
  'cart_adds_total',
  'cart_adds_self',
  'cart_adds_self_share',
  'purchases_total',
  'purchases_self',
  'purchases_self_share',
  'market_ctr',
  'self_ctr',
  'market_cvr',
  'self_cvr',
  'self_ctr_index',
  'self_cvr_index',
  'cart_add_rate_from_clicks_market',
  'cart_add_rate_from_clicks_self',
];

const ALL_COLUMNS_BY_KEY = new Map(ALL_COLUMNS.map((column) => [column.key, column]));
const IMPORTANT_COLUMNS: ColumnDef[] = IMPORTANT_KEYS
  .map((key) => ALL_COLUMNS_BY_KEY.get(key))
  .filter((column): column is ColumnDef => Boolean(column));

export { ALL_COLUMNS, IMPORTANT_COLUMNS };
